In [4]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
plt.style.use("fivethirtyeight")

In [1]:
!pip install joblib

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [34]:
class perceptron:
    #epochs = no_of_iterations
    def __init__(self,eta: float=None, epochs: int=None):
        self.weights = np.random.rand(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs # no of iterations
        
    def fit(self, x,y):
        self.x = x
        self.y = y
        # np.c_ is concatination
        x_with_bias = np.c_[self.x,-np.ones(len(self.x), 1)]
        print(f"X with bias : \n {x_with_bias}")
        
    
    

In [37]:
obj = perceptron(eta=0.01, epochs=10)

In [38]:
obj.eta

0.01

In [39]:
obj.weights

array([8.16170940e-05, 6.38021305e-05, 2.56990898e-05])

In [40]:
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [42]:
obj.fit(x,y)

TypeError: Cannot interpret '1' as a data type

In [6]:
np.random.rand(3) *1e-4

array([5.99642748e-05, 4.58421271e-05, 9.89474928e-06])

In [35]:
x = np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
y = np.ones((4,1))

In [14]:
np.c_[x,y] # concatination

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])