In [56]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
plt.style.use("fivethirtyeight")
import pandas as pd

In [1]:
!pip install joblib

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [76]:
class perceptron:
    #epochs = no_of_iterations
    def __init__(self,eta: float=None, epochs: int=None):
        self.weights = np.random.rand(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs # no of iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
        
        
    def activation_function(self, z):
        return np.where(z> 0, 1, 0) # if z > 0, than put 1 otherwise put 0
    
        
    
    def fit(self,x,y):
        self.x = x
        self.y = y
        # np.c_ is concatination
        x_with_bias = np.c_[self.x,-np.ones((len(self.x), 1))]
        print(f"X with bias : \n {x_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >>{epoch+1}")
            print("--"*10)
            
            z = self._z_outcome(x_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass : \n {y_hat}")
            self.error = self.y - y_hat
            print(f"error : \n{self.error}")
    
            
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T, self.error)
            print(f"updated weights after epoch : {epoch + 1}/{self.epochs} : \n {self.weights}")
            print(f"**"*10)
            
    def predict(self, x):
        x_with_bias = np.c_[x,-np.ones((len(x), 1))]
        z = self._z_outcome(x_with_bias, self.weights)
        return self.activation_function(z)

In [77]:
Or = {
   "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}
df_or = pd.DataFrame(Or)

df_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [78]:
def prepare_data(df, target_col = "y"):
    x = df.drop(target_col, axis = 1)
    y = df[target_col]
    return x, y 

In [79]:
x,y = prepare_data(df_or)
ETA = 0.1
EPOCHS = 10

model_or = perceptron(eta=ETA, epochs=EPOCHS)
model_or.fit(x,y)

X with bias : 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >>1
--------------------
predicted value after forward pass : 
 [0 0 0 0]
error : 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch : 1/10 : 
 [ 0.20000247  0.2000318  -0.29995801]
********************
--------------------
for epoch >>2
--------------------
predicted value after forward pass : 
 [1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch : 2/10 : 
 [ 0.20000247  0.2000318  -0.19995801]
********************
--------------------
for epoch >>3
--------------------
predicted value after forward pass : 
 [1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch : 3/10 : 
 [ 0.20000247  0.2000318  -0.09995801]
********************
--------------------
for epoch >>4
--------------------
predicted value after forward pass : 
 [1 1 1 1]
error : 
0   -1
1    0
2    0
3 

In [71]:
model_or.predict(x=[[0,0]])

array([0])

In [63]:
x, y = prepare_data(df_or)
x

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [64]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [44]:
obj = perceptron(eta=0.01, epochs=10)

In [45]:
obj.eta

0.01

In [46]:
obj.weights

array([1.70421875e-05, 2.65715761e-05, 3.64411462e-05])

In [47]:
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [48]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [49]:
obj.fit(x,y)

X with bias : 
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [6]:
np.random.rand(3) *1e-4

array([5.99642748e-05, 4.58421271e-05, 9.89474928e-06])

In [35]:
x = np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
y = np.ones((4,1))

In [14]:
np.c_[x,y] # concatination

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [50]:
z = 34

In [53]:
np.where(z> 0, 1, 0)

array(0)

In [52]:
z = -8

In [54]:
#while training = forward + backword
#while prediction =  Forward